export const ADD_PRODUCT = 'AGREGAR_PRODUCTO';
export const ADD_PRODUCT_SUCCESS = 'AGREGAR_PRODUCTO_EXITO';
export const ADD_PRODUCT_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const START_PRODUCTS_DOWNLOAD = 'COMENZAR_DESCARGA_PRODUCTOS';
export const DOWNLOAD_PRODUCTS_SUCCESS = 'DESCARGA_PRODUCTOS_EXITO';
export const DOWNLOAD_PRODUCTS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';

export const GET_PRODUCT_DELETE = 'OBTENER_PRODUCTO_ELIMINAR';
export const PRODUCT_REMOVED_SUCCESS = 'PRODUCTO_ELIMINADO_EXITO';
export const PRODUCT_REMOVED_ERROR = 'PRODUCTO_ELIMINADO_ERROR';

export const GET_PRODUCT_EDIT = 'OBTENER_PRODUCTO_EDITAR';
export const START_PRODUCT_EDITION = 'COMENZAR_EDICION_PRODUCTO';
export const EDITED_PRODUCT_SUCCESS = 'PRODUCTO_EDITADO_EXITO';
export const EDITED_PRODUCT_ERROR = 'PRODUCTO_EDITADO_ERROR';

export const SHOW_ALERT = 'MOSTRAR_ALERTA';
export const HIDE_ALERT = 'OCULTAR_ALERTA';